fix(deps): Use pug instead of jade
zaach/jsxgettext pull request #123
Opened 2018-08-23 10:33 UTC by shane-tomlinson

The jade module was discontinued and had some `npm audit` warnings.

This replaces jade with pug and updates the jade parser based
on the updated AST format.

There was a problem with the original tests/outputs/jade.pot,
the two modified lines were actually incorrect when comparing
with the source.

@zaach - r?

2018-09-17 12:56 UTC, vladikoff requested changes

2018-09-17 12:56 UTC, vladikoff commented on test/outputs/jade.pot
>  msgid "because jade generally doesn't care"
Should we rephrase this test? and file names too?

2018-09-25 09:58 UTC, shane-tomlinson commented
@vladikoff - updated!

2018-09-25 14:09 UTC, vladikoff commented
Landed in https://github.com/mozilla/jsxgettext/releases/tag/v0.11.0

Ref: https://github.com/mozilla/jsxgettext

We can uplift to this account later if needed

2019-12-15 22:08 UTC, closed without merging